speech/urls.py
from django.urls import path

from . import views

app_name = 'speech'
urlpatterns = [
    path('', views.index, name='index'),
    path('informedConsentDocument/', views.informedConsentDocument, name='informedConsentDocument'),
    path('healthAndDemographicsForm/', views.healthAndDemographicsForm, name='healthAndDemographicsForm'),
    path('practice/', views.practice, name='practice'),
    path('initialize/', views.initialize, name='initialize'),
    path('practiceCompleteAck/', views.practiceCompleteAck, name='practiceCompleteAck'),
    path('practiceRetry/', views.practiceRetry, name='practiceRetry'),
    path('practiceComplete/', views.practiceComplete, name='practiceComplete'),
    path('task/', views.task, name='task'),
    path('taskComplete/', views.taskComplete, name='taskComplete'),
    path('postTaskSurvey/', views.postTaskSurvey, name='postTaskSurvey'),
    path('success/', views.success, name='success'),
    path('error/', views.error, name='error'),
]

speechstroop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
#    path('admin/', admin.site.urls),
    path('speech/', include('speech.urls')),
]

speech/forms.py
from django.forms import ModelForm, SelectDateWidget, CheckboxSelectMultiple, forms
from .models import StroopSession
from datetime import datetime

# # Limits for birthdate years
# MIN_AGE = 18
# MAX_AGE = 100
#
# currYear = datetime.now().year
# MIN_YEAR = currYear - MAX_AGE - 1
# MAX_YEAR = currYear - MIN_AGE
#
# GENDER_CHOICES=[
#     ('male', 'Male'),
#     ('female', 'Female'),
#     ('other', 'Other')
# ]

class InformedConsentDocumentForm(ModelForm):
    # Function below to set signed date as readonly
    # def __init__(self, *args, **kwargs):
    #    super(InformedConsentDocumentForm, self).__init__(*args, **kwargs)
    #    self.fields['informed_consent_signed_date_time'].widget.attrs['readonly'] = True

    class Meta:
        model = StroopSession
        # fields = ['informed_consent_signature', 'informed_consent_signed_date_time']
        fields = []

class HealthAndDemographicsForm(ModelForm):
    class Meta:
        model = StroopSession
        fields = ['years_of_education', 'racial_categories', 'is_latino', 'household_income', 'computer_type', 'microphone_type', 'hours_on_current_computer', 'computer_os', 'computer_screen_width_px', 'computer_screen_height_px', 'additional_comments']

class HealthAndDemographicsFormWithAge(ModelForm):
    class Meta:
        model = StroopSession
        fields = ['age', 'years_of_education', 'racial_categories', 'is_latino', 'household_income', 'computer_type', 'microphone_type', 'hours_on_current_computer', 'computer_os', 'computer_screen_width_px', 'computer_screen_height_px', 'additional_comments']
        # fields = ['birthdate', 'gender', 'years_of_education', 'dominant_hand', 'alert_time_of_day', 'racial_categories', 'is_latino', 'is_english_first_language', 'first_language', 'learn_english_before_age_5', 'age_learned_english', 'additional_comments']
        # widgets = {
        #     'birthdate': SelectDateWidget(years = list(range(MAX_YEAR, MIN_YEAR, -1))),
        #     # 'racial_categories': CheckboxSelectMultiple
        # }
        # fields = '__all__'
    # birthdate = forms.DateField(label='Birthdate')
    # gender = forms.CharField(label='Gender', widget=forms.Select(choices=GENDER_CHOICES))

    # def clean(self):
    #     print("************ clean() called!")
    #
    #     # First language
    #     is_english_first_language = self.cleaned_data.get('is_english_first_language')
    #     first_language = self.cleaned_data.get('first_language')
    #
    #     # Age learned english
    #     learn_english_before_age_5 = self.cleaned_data.get('learn_english_before_age_5')
    #     age_learned_english = self.cleaned_data.get('age_learned_english')
    #
    #     if is_english_first_language == StroopSession.NO:
    #         print("***clean(): english not first language. Checking first language")
    #         if first_language == '':
    #             print("***clean(): english not first language. first language was empty. Error.")
    #             msg = forms.ValidationError("The following field is required:")
    #             self.add_error('first_language', msg)
    #     else:
    #         # Keep the database consistent. The user may have
    #         # submitted a shipping_destination even if shipping
    #         # was not selected
    #         self.cleaned_data['first_language'] = ''
    #
    #     if learn_english_before_age_5 == StroopSession.NO:
    #         print("***clean(): learned english after age 5. Checking age")
    #         if age_learned_english == 0:
    #             print("***clean(): english not first language. age learned english == 0. Error")
    #             msg = forms.ValidationError("The following field is required:")
    #             self.add_error('age_learned_english', msg)
    #     else:
    #         # Keep the database consistent. The user may have
    #         # submitted a shipping_destination even if shipping
    #         # was not selected
    #         self.cleaned_data['age_learned_english'] = 0
    #
    #     return self.cleaned_data

class PostTaskForm(ModelForm):
    class Meta:
        model = StroopSession
        fields = ['done_stroop_previously', 'post_task_comments']

speech/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from speech.models import Trial, StroopSession
from django.utils import timezone
import pytz
from random import shuffle, randint
from datetime import datetime
from django.conf import settings
from django.core.mail import send_mail

from .forms import HealthAndDemographicsForm, HealthAndDemographicsFormWithAge, PostTaskForm, InformedConsentDocumentForm

########################################
############## Parameters ##############
########################################
# Trial Generation Parameters
NUM_PRACTICE_CONGRUENT = 6
NUM_PRACTICE_INCONGRUENT = 6
NUM_PRACTICE_NEUTRAL = 6

NUM_PRACTICE_WITH_HINTS = 9

NUM_CONGRUENT = 54
NUM_INCONGRUENT = 54
NUM_NEUTRAL = 48

# Put the break in the middle of the trials
NUM_PRACTICE_TRIALS = NUM_PRACTICE_CONGRUENT + NUM_PRACTICE_INCONGRUENT + NUM_PRACTICE_NEUTRAL
NUM_TRIALS_BEFORE_BREAK = NUM_PRACTICE_TRIALS + (NUM_CONGRUENT + NUM_INCONGRUENT + NUM_NEUTRAL) / 2

# Duration of break
BREAK_DURATION_SEC = 30

# Duration for reading informed consent document (seconds)
INFORMED_CONSENT_DOCUMENT_READ_DURATION_SEC = 10

# Prefix for all completion codes
# Completion codes are "<Prefix><Subject Number, no padding>"
COMPLETION_CODE_PREFIX = "F7J"

# Completion Link
PROLIFIC_COMPLETION_LINK = "https://app.prolific.co/submissions/complete?cc=5EA9939D"
SUBJECT_POOL_COMPLETION_LINK = "https://wupsych.sona-systems.com/webstudy_credit.aspx?experiment_id=285&credit_token=35945ffab5b04fcb996627b0a48d007c&survey_code="
    # Fill out survey_code with the "PROLIFIC_PID" in https://wupsych.sona-systems.com/webstudy_credit.aspx?experiment_id=285&credit_token=35945ffab5b04fcb996627b0a48d007c&survey_code=XXXX

# Maximum number of digits for subject number (5 means up to 99,999)
MAX_NUM_SUBJECT_DIGITS = 5 # Up to 99,999 subjects
MAX_NUM_TRIAL_DIGITS = 3   # Up to 999 trials

# Practice success criteria
PRACTICE_MIN_ACCURACY_THRESHOLD = 0.75

# Debug print enable
DEBUG_NONE = 0
DEBUG_LOW = 1
DEBUG_MEDIUM = 2
DEBUG_HIGH = 3

DEBUG_LEVEL = DEBUG_MEDIUM

# Debug mode switch (shortens number of trials and timers)
if settings.DEBUG:
    # OPTION to turn debug mode on/off in development
    DEBUG = True
    # DEBUG = False
else:
    # Force debug mode off on deployment
    ## DO NOT CHANGE ##
    DEBUG = False
    ## DO NOT CHANGE ##

print("views.py: settings.DEBUG set to " + str(settings.DEBUG) + " and DEBUG set to " + str(DEBUG))

############ TEST CODE ONLY #################
if (DEBUG):
    INFORMED_CONSENT_DOCUMENT_READ_DURATION_SEC = 5

    NUM_PRACTICE_CONGRUENT = 1
    NUM_PRACTICE_INCONGRUENT = 1
    NUM_PRACTICE_NEUTRAL = 1
    NUM_PRACTICE_WITH_HINTS = 1
    NUM_CONGRUENT = 2
    NUM_INCONGRUENT = 2
    NUM_NEUTRAL = 2
    NUM_PRACTICE_TRIALS = NUM_PRACTICE_CONGRUENT + NUM_PRACTICE_INCONGRUENT + NUM_PRACTICE_NEUTRAL
    NUM_TRIALS_BEFORE_BREAK = NUM_PRACTICE_TRIALS + (NUM_CONGRUENT + NUM_INCONGRUENT + NUM_NEUTRAL) / 2
    BREAK_DURATION_SEC = 5

########################################
########################################

# Constants for accessing trialArray data
TRIAL_TYPE = 0;
INK_COLOR = 1;
WORD = 2;

########################################
def index(request):
    if (DEBUG_LEVEL >= DEBUG_MEDIUM):
        print("*** index() called  ***")
    request.session['newSession'] = True
    request.session['PROLIFIC_PID'] = request.GET.get('PROLIFIC_PID', 'PROLIFIC_PID_MISSING')
    request.session['SESSION_ID'] = request.GET.get('SESSION_ID', 'SESSION_ID_MISSING')
    request.session['STUDY_ID'] = request.GET.get('STUDY_ID', 'STUDY_ID_MISSING')

    if (DEBUG_LEVEL >= DEBUG_LOW):
        print("*** index(): PROLIFIC_PID: " + request.session['PROLIFIC_PID'] + " SESSION_ID: " + request.session['SESSION_ID'] + " STUDY_ID: " + request.session['STUDY_ID'] + " ***")

    return render(request, 'speech/index.html')

########################################
def informedConsentDocument(request):
    if (DEBUG_LEVEL >= DEBUG_MEDIUM):
        print("*** informedConsentDocument() called  ***")

    signingStatus = "Not signed"

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        if (DEBUG_LEVEL >= DEBUG_HIGH):
            print("*** informedConsentDocument(): method was POST  ***")
        # create a form instance and populate it with data from the request:
        form = InformedConsentDocumentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            if (DEBUG_LEVEL >= DEBUG_HIGH):
                print("*** informedConsentDocument(): form was valid  ***")
            # process the data in form.cleaned_data as required
            num_practice_trials = NUM_PRACTICE_CONGRUENT + NUM_PRACTICE_INCONGRUENT + NUM_PRACTICE_NEUTRAL
            totalTrials = num_practice_trials + NUM_CONGRUENT + NUM_INCONGRUENT + NUM_NEUTRAL

            # Generate current session
            currSubjectNumStr = str(len(StroopSession.objects.all()))
            currSession = StroopSession(
                subject_id = "test" + currSubjectNumStr.zfill(MAX_NUM_SUBJECT_DIGITS),

                prolific_pid = request.session['PROLIFIC_PID'],
                session_id = request.session['SESSION_ID'],
                study_id = request.session['STUDY_ID'],

                num_practice_trials = num_practice_trials,
                num_trials_before_break = NUM_TRIALS_BEFORE_BREAK,
                break_duration_sec = BREAK_DURATION_SEC,
                num_trials = totalTrials,
                valid = False,
                # completion_code = COMPLETION_CODE_PREFIX + currSubjectNumStr,

                informed_consent_signed = True,
                # informed_consent_signature = form.cleaned_data['informed_consent_signature'],
                informed_consent_signed_date_time = datetime.now(),
                # informed_consent_signed_date_time = form.cleaned_data['informed_consent_signed_date_time'],
            )
            currSession.save()

            if (DEBUG_LEVEL >= DEBUG_HIGH):
                print("*** Parsed currSession data is: " + str(currSession))

            # Save session info
            request.session['currSessionPK'] = currSession.subject_id
            # request.session['completionCode'] = currSession.completion_code
            request.session.modified = True

            #### DEBUG ###
            if (DEBUG_LEVEL >= DEBUG_HIGH):
                print("[" + str(currSession.subject_id) + "] informedConsentDocument(): Received POST and populated StroopSession:" + str(form))

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('speech:healthAndDemographicsForm'))

        if (DEBUG_LEVEL >= DEBUG_MEDIUM):
            print("*** informedConsentDocument(): form was NOT valid  ***")

    # if a GET (or any other method) we'll create a blank form
    else:
        if (DEBUG_LEVEL >= DEBUG_HIGH):
            print("*** informedConsentDocument(): method was not POST  ***")
        # form = InformedConsentDocumentForm(initial={'informed_consent_signed_date_time': datetime.now()})
        form = InformedConsentDocumentForm()

    # First, check if they had just started a new session
    if (request.session['newSession'] == True):
        request.session['newSession'] = False
        consentSigned = False
    elif (isInformedConsentSigned(request)):
        # Update form with the date and time signed
        currSession = StroopSession.objects.get(pk=request.session['currSessionPK'])
        signingStatus = 'Signed ' + currSession.informed_consent_signed_date_time.strftime("%m/%d/%Y, %H:%M:%S") + ' (UTC time)'
        consentSigned = True
    else:
        consentSigned = False

    return render(request, 'speech/informedConsentDocument.html', {'form': form, 'consentSigned': consentSigned, 'signingStatus': signingStatus, 'readDurationSec':INFORMED_CONSENT_DOCUMENT_READ_DURATION_SEC})

########################################
def healthAndDemographicsForm(request):
    if (DEBUG_LEVEL >= DEBUG_MEDIUM):
        print("*** healthAndDemographicsForm() called  ***")

    # Enforce that informed consent was signed
    if (not isInformedConsentSigned(request)):
        if (DEBUG_LEVEL >= DEBUG_HIGH):
            print("*** healthAndDemographicsForm(): ERROR: Informed consent NOT signed. Redirecting to form... ***")
        return HttpResponseRedirect(reverse('speech:informedConsentDocument'))
    else:
        if (DEBUG_LEVEL >= DEBUG_HIGH):
            print("*** healthAndDemographicsForm(): PASSED: Informed consent signed. Continuing... ***")

    try:
        # if this is a POST request we need to process the form data
        if request.method == 'POST':
            if (DEBUG_LEVEL >= DEBUG_HIGH):
                print("*** healthAndDemographicsForm(): method was POST  ***")
            # create a form instance and populate it with data from the request:
            # Switch based on SESSION_ID
            if (request.session['SESSION_ID'] == 'SUBJECT_POOL'):
                form = HealthAndDemographicsFormWithAge(request.POST)
            else:
                form = HealthAndDemographicsForm(request.POST)

            # check whether it's valid:
            if form.is_valid():
                if (DEBUG_LEVEL >= DEBUG_MEDIUM):
                    print("*** healthAndDemographicsForm(): form was valid  ***")
                # process the data in form.cleaned_data as requiredSUBJECT_POOL
                currSession = StroopSession.objects.get(pk=request.session['currSessionPK'])

                #### DEBUG ###
                if (DEBUG_LEVEL >= DEBUG_HIGH):
                    print("[" + str(currSession.subject_id) + "] healthAndDemographicsForm(): Received POST and populated StroopSession:" + str(form))

                # currSession.birthdate = form.cleaned_data['birthdate']

speech/templates/speech/computer_data_test.html
<html>
  <body>
    <p>hello!</p>
    <input type="text" id="outputBox">
  </body>

  <script>
    // document.getElementById("outputBox").value = .toString();
    console.log(navigator);
    console.log(screen);
  </script>
</html>

speech/templates/speech/datepickertest.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Static Example</title>

    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

  </head>
  <body>

    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
      <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
      <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
      </div>
    </div>

    <script>
      $(function () {
        $("#datetimepicker1").datetimepicker();
      });
    </script>

  </body>
</html>

speech/templates/speech/error.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <title>Error</title>

    <link rel="stylesheet" href="{% static 'speech/style.css' %}">
    <!--[if lt IE 9]>
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>
      <h1>Sorry, an internal error has occurred!</h1>

      <img src="{% static 'speech/images/dead-computer.png' %}" alt="Error">

      <h2>You may try returning to the <a href="{% url 'speech:index' %}">start</a> and trying again.<h2>

      <!-- <p>If you believe this was in error, you may contact us at ________.</p> -->
  </body>
</html>

speech/templates/speech/fullscreen_test.html
<html>
<body>
<button id="goFS">Go fullscreen</button>
</body>
<script>
  var goFS = document.getElementById("goFS");
  goFS.addEventListener("click", function() {
      document.body.requestFullscreen();
  }, false);
</script>
</html>

speech/templates/speech/index.html
{% load static %}

﻿<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <title>Stroop Task</title>

    <link rel="stylesheet" href="{% static 'speech/style.css' %}">
  </head>

  <body>
    <h1>Stroop Task</h1>


    <h3>Instructions:</h3>
    <p>You will see words on the screen written in different color ink. When a word is shown, say the color of the <b>ink</b> out loud (not what the text says). This task will take 15-20 minutes to complete.</p>


    <h3>Minimum requirements:</h3>
    <ul>
      <li id="browserRequirement">Google Chrome web browser</li>
      <ul id="browserRequirementDetail" style="display: none; color: red;">
        <li>You can install Google Chrome from Google's website, <a href="https://www.google.com/chrome/">here</a>. Once installed, reopen <a href="{% url 'speech:index' %}">this webpage</a> in Google Chrome.</li>
      </ul>
      <li id="micRequirement">Microphone</li>
      <ul id="micRequirementDetail" style="display: none; color: red;">
        <li>At the top-right of the window, next to the URL, click the camera icon and allow the microphone. Then refresh the page. It should look like below:</li>
        <!-- <img src="{% static 'speech/images/Microphone_blocked.png' %}" alt="Microphone Blocked"> -->
        <img src="{% static 'speech/images/Microphone_allowed-annotated.png' %}" alt="Microphone Allowed">
      </ul>
      <li>If using a laptop, plug it into a wall outlet or make sure you have enough battery for 30 minutes</li>
      <li>Proficient in English</li>
      <li>Quiet surroundings</li>
    </ul>
    <br>

    <p>When prompted, click "Allow Microphone."</p>

    <!-- <a href="{% url 'speech:practice' %}"><button id="startButton" type="button">Continue Instructions</button> -->
    <button id="startButton" type="button" onclick="onButtonClick();">Click and then say "Continue"</button>
    <!-- <input id="startButton" type="button" value="Click and say Continue" onclick="onButtonClick();" /> -->

  </body>

  <script src="{% static 'speech/indexScript.js' %}"></script>
</html>

speech/templates/speech/postTaskSurvey.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <title>Complete</title>

    <link rel="stylesheet" href="{% static 'speech/style.css' %}">
  </head>

  <body>
      <h1>Done!</h1>

      <p>Good work! You have completed the task. If you had any difficulty during the task, please explain in the text box below. Click Continue once you are done to receive credit on Prolific.</p>

      <br>

      <form action="{% url 'speech:postTaskSurvey' %}" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Continue">
      </form>

  </body>
</html>

speech/templates/speech/practice.html
{% load static %}

﻿<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <title>Stroop Task</title>

    <link rel="stylesheet" href="{% static 'speech/style.css' %}">
  </head>

  <body>
      <h1>Stroop Task Practice</h1>

      <h3>Instructions:</h3>
      <p>You will see words presented in different colored ink. It is your job to ignore the word and say the ink color aloud.</p>
      <p>The 4 colors you will see are:</p>
      <ul><font color="red" style="background-color:red;"><b>____</b></font> If you see a word written in this color, please say "RED".</ul>
      <ul><font color="DodgerBlue" style="background-color:DodgerBlue;"><b>____</b></font> If you see a word written in this color, please say "BLUE".</ul>
      <ul><font color="green" style="background-color:green;"><b>____</b></font> If you see a word written in this color, please say "GREEN".</ul>
      <ul><font color="yellow" style="background-color:yellow;;"><b>____</b></font> If you see a word written in this color, please say "YELLOW".</ul>

      <br>

      <p>Remember to say the color of the ink out loud, not the word.</p>

      <p>Note: If the colors are too dark to see, please turn up the brightness of your monitor.</p>

      <p>We will start with 18 practice trials. The first 9 practice trials will have feedback, afterwards you will be on your own.</p>

      <a href="{% url 'speech:initialize' %}"><button id="startButton" type="button">Start Practice</button></a>
    </body>

    <script src="{% static 'speech/indexScript.js' %}"></script>
</html>

speech/templates/speech/practiceComplete.html
{% load static %}

﻿<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <title>Practice Complete</title>

    <link rel="stylesheet" href="{% static 'speech/style.css' %}">
  </head>

  <body>
      <h1>Practice Complete</h1>

      <p style="text-align:center;">You have completed the practice trials. Click the button below to start the actual trials.</p>

      <a href="{% url 'speech:practiceCompleteAck' %}"><button id="startButton" type="button">Start Trials</button></a>
    </body>

    <video width="1" height="1" loop muted autoplay>
      <source src="{% static 'speech/noop.mp4' %}" type="video/mp4">
      Your browser does not support the video tag. You will have to move the mouse periodically to prevent the screen from turning off during the task.
    </video>

    <script src="{% static 'speech/indexScript.js' %}"></script>
</html>

speech/templates/speech/practiceRetry.html
{% load static %}

﻿<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <title>Practice Retry</title>

    <link rel="stylesheet" href="{% static 'speech/style.css' %}">
  </head>

  <body>
      <h1>Practice Complete</h1>

      <p>You have completed the practice session. Unfortunately, you did not recieve an accuracy of {{ percent_required }}% or higher and will need to repeat the practice session.</p>

      <br>

      <p>If you had significant issues with the speech recognition during practice, please try (1) moving closer to the computer, (2) speaking louder and clearer, and (3) making sure the microphone is unobstructed.</p>

      <a href="{% url 'speech:practice' %}"><button id="startButton" type="button">Click here to return to practice</button></a>
    </body>

    <video width="1" height="1" loop muted autoplay>
      <source src="{% static 'speech/noop.mp4' %}" type="video/mp4">
      Your browser does not support the video tag. You will have to move the mouse periodically to prevent the screen from turning off during the task.
    </video>

    <script src="{% static 'speech/indexScript.js' %}"></script>
</html>

speech/templates/speech/success.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <title>Complete</title>

    <link rel="stylesheet" href="{% static 'speech/style.css' %}">
  </head>

  <body>
      <h1>Success! Thank you for participating!</h1>

      <img src="{% static 'speech/images/thumbs_up.png' %}" alt="Success Image">

      <br><br>

      <p id="countdownText" style="text-align: center;"></p>

  </body>

  <script>
    var countdown = 3;

    setTimeout("location.href = '{{ prolificCompletionLink }}';",countdown * 1000);

    updateCountdown();

    function updateCountdown()
    {
      document.getElementById("countdownText").innerHTML = "You will be redirected in " + countdown + " seconds back to {{ testingSite }}.";
      countdown -= 1;
      if (countdown > 0)
      {
        window.setTimeout(updateCountdown, 1000);
      }
    }
  </script>
</html>